### ISSUE TITLE
Animations and autoclear not triggering

### ISSUE THREAD

**Issue by victor-nitu** [mansona/ember-cli-notifications#24]
Please note this can also be caused by a lack of documentation from your side, respectively understanding of Ember CLI internals from mine.

Everything works fine in my project regarding the notifications, except they are not animated and the autohide feature doesn't work at all. Font Awesome is working.

This could be caused by missing bits in the Brocfile.js, which would make it my fault. I'd be happy to know which is the correct (and complete) way to do it, then I promise a PR with a README update :wink:

**Comment by victor-nitu** [comment]
Just a quick update: under Firefox everything seems fine, the problem persists with Chrome/Chromium. Still don't know if it's a Chrome problem or, more generally, a Webkit one.

**Comment by ynnoj** [comment]
@nightsh Try out the new version I just published [(1.1.4)](https://github.com/Blooie/ember-cli-notifications/releases/tag/v1.1.4) and let me know if that fixes your animation issues.

**Comment by victor-nitu** [comment]
Just tried with 1.1.4, still not animated. Anything I can help you with? You can see what I have done [in the project's repository](https://github.com/thesponge/kep/tree/develop).

**Comment by mansona** [comment]
@nightsh We've just changes some internals on how CSS is processed, can you try it again and let us know if you have any luck. 

If that doesn't work we will probably have to work on coming up with a basic test example of an app that has the same issues you're experiencing so we can get to the bottom of this :+1:

**Comment by victor-nitu** [comment]
@mansona Not happening, sorry. I'll try to build a minimal working example of the fail today, in the meantime you can have a look at the project's [package.json](https://github.com/thesponge/kep-frontend/blob/master/package.json) and the related files, maybe I'm missing something.

**Comment by ynnoj** [comment]
@nightsh Did you try the new version? We bumped the package to 1.2.0 yesterday.

**Comment by victor-nitu** [comment]
@ynnoj yes, I tried with 1.2.0 right now. Consider the actual package.json, but with the 1.2.0 version of ember-cli-notifications.

**Comment by mansona** [comment]
Oh wait, the project you're working on is open source (or at least public). If I just run that repo without any backend would I be able to trigger the offending notification? If you could put a test button somewhere on the page I could test it in situ, i.e. no need to create a separate test example

**Comment by victor-nitu** [comment]
@mansona Updated + added test button. See [the frontend develop branch](https://github.com/thesponge/kep-frontend/tree/develop).

**Comment by mansona** [comment]
@ynnoj got as far as this working on @nightsh's repo (with a bit of difficulty because of node-sass and io.js) but I got this error for the notification: 

https://cloudup.com/cu2fTzWFqnV

Is it missing auto-prefixer or something?

**Comment by ynnoj** [comment]
#28 should fix the prefix issues.

**Comment by mansona** [comment]
Hi @nightsh I have verified that version 1.2.1 does indeed fix the issues you were having :+1:
